language: node_js
node_js:
  - "12.14.1"
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
install:
  - npm install
before_script:
  - npm run build
script:
  - npm run test
  - npm install codecov -g
after_success:
  - codecov --token="660f3c84-d629-4418-8c23-b7ca4b02cc36"