language: node_js
node_js:
  - "10.16.0"
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
install:
  - npm install
before_script:
  - npm run build
script:
  - npm run test